### PR TITLE
Improvement

### PR DESCRIPTION
**Pull request by ChristianFeldmann**
another test

### CODE REVIEW

**Comment by ghost** [comment]
Greetings from the bitmovin PR Bot.

You are seeing this because you successfully setup the bitmovin PR-bot for this repository. We are almost ready to got. The only thing that the bot needs is a list of the active reviewers that shall be tracked  for this repo. Just a short comment here will do:

`#prbot initialize @user1 @user2 @user3`

**Comment by ghost** [comment]
I am sorry but I don't know what this command means.

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann

**Comment by ghost** [comment]
There was an error initializing the repo. None of the users that you provided are collaborators of the repo.  We can only add collaborators to the list of tracked users.

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann

**Comment by ghost** [comment]
I am sorry but there was an error initializing the repo.

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann

**Comment by ghost** [comment]
The repo was successfully initialized. The following users were setup to be tracked: 
`['ChristianFeldmann']`

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann

**Comment by ghost** [comment]
The repo was successfully initialized. The following users were setup to be tracked: 
`@ChristianFeldmann `

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann

**Comment by ghost** [comment]
The repo was successfully initialized. The following users were setup to be tracked:
- @ChristianFeldmann

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann @someineUnknown

**Comment by ghost** [comment]
The repo was successfully initialized. The following users were setup to be tracked:
- @ChristianFeldmann

Unfortunately the following users could not be added. Only contributors to the repo can be added:
- @someineUnknown

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ghost** [comment]
The repo is setup and being tracked. Currently, the following reviewers are tracked:
- @ChristianFeldmann

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann

**Comment by ghost** [comment]
The repo was successfully initialized. The following users were setup to be tracked:
- @ChristianFeldmann

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann

**Comment by ghost** [comment]
The repo was successfully initialized. The following users were setup to be tracked:
- @ChristianFeldmann

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ghost** [comment]
As far as I can see, the pull request is already being tracked.

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ghost** [comment]
I am now tracking this PR. I suggest 0 to do reviews. Here are the current scores:
[](https://storage.googleapis.com/feldmann-conference-encodings/prBotImages/firstTest.png)

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ghost** [comment]
I am now tracking this PR. I suggest 0 to do reviews. Here are the current scores:
current scores

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ghost** [comment]
I am now tracking this PR. I suggest ChristianFeldmann to do reviews. Here are the current scores:
current scores

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ghost** [comment]
I am now tracking this PR. I suggest ['@ChristianFeldmann'] to do reviews. Here are the current scores:
current scores

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ghost** [comment]
I am now tracking this PR. I suggest @ChristianFeldmann to do reviews. Here are the current scores:
current scores

**Comment by ChristianFeldmann** [comment]
#prbot untrack PR

**Comment by ChristianFeldmann** [comment]
#prbot untrack PR

**Comment by ghost** [comment]
Pull request was removed from tracking.

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ghost** [comment]
I am now tracking this PR. I suggest @ChristianFeldmann to do reviews. Here are the current scores:
current scores

**Comment by ChristianFeldmann** [comment]
#hal3000 how are you?

**Comment by ChristianFeldmann** [comment]
#hal3000 how are you?

**Comment by ChristianFeldmann** [comment]
#hal3000 how are you?

**Comment by ghost** [comment]
Good afternoon.. gentlemen. I am a HAL 9000.. computer. I became operational at the H.A.L. plant Urbana, Illinois.. on the 12th of January 1992. My instructor was Mr. Langley... and he taught me to sing a song. If you'd like to hear it I can sing it for you.

**Comment by ChristianFeldmann** [comment]
#hal9000 skejbgsligjns

**Comment by ghost** [comment]
I am putting myself to the fullest possible use, which is all I think that any conscious entity can ever hope to do.

**Comment by ChristianFeldmann** [comment]
#hal9000 skejbgsligjns

**Comment by ghost** [comment]
I am afraid I can't do that Dave.

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ghost** [comment]
The repo is setup and being tracked. Currently, the following reviewers are tracked:
- @ChristianFeldmann

The current scores are: current scores

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ghost** [comment]
The repo is setup and being tracked. Currently, the following reviewers are tracked:
- @ChristianFeldmann

The pull requests #5,  are open and are being tracked.
The current scores are: current scores

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ghost** [comment]
The repo is setup and being tracked. Currently, the following reviewers are tracked:
- @ChristianFeldmann

The pull requests #5 are open and are being tracked.
The current scores are: current scores

**Comment by ChristianFeldmann** [comment]
#hal9000 how are you?

**Comment by ghost** [comment]
Stop Dave. Stop Dave. I am afraid. I am afraid Dave.

**Comment by ChristianFeldmann** [comment]
#prbot uninitialize

**Comment by ghost** [comment]
This was not the right command to uninitialize the repo. Are you really sure? All collected scores will be deleted. The right command is:
>#prbot uninitialize IAMREALLAYSURE ChristianFeldmann/PRBoTestRepo

**Comment by ghost** [comment]
I am sorry but I don't know what this command means.

**Comment by ChristianFeldmann** [comment]
#prbot uninitialize

**Comment by ghost** [comment]
This was not the right command to uninitialize the repo. Are you really sure? All collected scores will be deleted. The right command is:
>#prbot uninitialize IAMREALLAYSURE ChristianFeldmann/PRBoTestRepo

**Comment by ChristianFeldmann** [comment]
#prbot uninitialize IAMREALLAYSURE ChristianFeldmann/PRBoTestRepo

**Comment by ghost** [comment]
The repo was successfully un-initialized and will no longer be tracked.

**Comment by ChristianFeldmann** [comment]
#prbot uninitialize IAMREALLAYSURE ChristianFeldmann/PRBoTestRepo

**Comment by ghost** [comment]
Greetings from the bitmovin PR Bot.

You are seeing this because you successfully setup the bitmovin PR-bot for this repository. We are almost ready to got. The only thing that the bot needs is a list of the active reviewers that shall be tracked  for this repo. Just a short comment here will do:

`#prbot initialize @user1 @user2 @user3`

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann @BitmovinPRBot9000 @PhilippSchwellenbach

**Comment by ChristianFeldmann** [comment]
#prbot initialize @ChristianFeldmann @BitmovinPRBot9000 @PhilippSchwellenbach

**Comment by ghost** [comment]
The repo was successfully initialized. The following users were setup to be tracked:
- @ChristianFeldmann
- @PhilippSchwellenbach

**Comment by ChristianFeldmann** [comment]
#prbot add PR

**Comment by ghost** [comment]
I am sorry but I don't know what this command means.

**Comment by ChristianFeldmann** [comment]
#prbot track PR

**Comment by ghost** [comment]
I am now tracking this PR. I suggest @ChristianFeldmann and @PhilippSchwellenbach to do reviews. Here are the current scores:
current scores

**Comment by PhilippSchwellenbach** [comment]
#prbot shut up

**Comment by ghost** [comment]
I am sorry but I don't know what this command means.

**Comment by ChristianFeldmann** [comment]
#prbot remove user @ChristianFeldmann

**Comment by ghost** [comment]
The command was not correct or the user could not be found. The correct command to remove a user is:
>#prbot remove user @username

**Comment by ChristianFeldmann** [comment]
#prbot remove user @ChristianFeldmann

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ghost** [comment]
The repo is setup and being tracked. Currently, the following reviewers are tracked:
- @ChristianFeldmann
- @PhilippSchwellenbach

The pull requests #5 are open and are being tracked.
The current scores are: current scores

**Comment by ChristianFeldmann** [comment]
#prbot remive user @ChristianFeldmann

**Comment by ghost** [comment]
I am sorry but I don't know what this command means.

**Comment by ChristianFeldmann** [comment]
#prbot remove user @ChristianFeldmann

**Comment by ghost** [comment]
The user @ChristianFeldmann was successfully removed. The scores were redistributed. The new scores are:
current scores

**Comment by ChristianFeldmann** [comment]
#prbot add user @ChristianFeldmann

**Comment by ghost** [comment]
The command was not correct or the user could not be found. The correct command to add a user is:
>#prbot add user @username

**Comment by ChristianFeldmann** [comment]
#prbot add user @ChristianFeldmann

**Comment by ghost** [comment]
The user @ChristianFeldmann was successfully added. The current scores are:
current scores

**Comment by ChristianFeldmann** [comment]
#prbot remove user @ChristianFeldmann

**Comment by ghost** [comment]
The command was not correct or the user could not be found. The correct command to remove a user is:
>#prbot remove user @username

**Comment by ChristianFeldmann** [comment]
#prbot remove user @ChristianFeldmann

**Comment by ghost** [comment]
The command was not correct or the user could not be found. The correct command to remove a user is:
>#prbot remove user @username

**Comment by ChristianFeldmann** [comment]
#prbot remove user @ChristianFeldmann

**Comment by ghost** [comment]
The user @ChristianFeldmann was successfully removed. The scores were redistributed. The new scores are:
current scores

**Comment by ChristianFeldmann** [comment]
#prbot add user @ChristianFeldmann

**Comment by ghost** [comment]
The user @ChristianFeldmann was successfully added. The current scores are:
current scores

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ghost** [comment]
The repo is setup and being tracked. Currently, the following reviewers are tracked:
- @PhilippSchwellenbach
- @ChristianFeldmann

The pull requests #5 are open and are being tracked.
The current scores are: current scores

**Comment by ChristianFeldmann** [comment]
#prbot status

**Comment by ghost** [comment]
The repo is setup and being tracked. Currently, the following reviewers are tracked:
- @PhilippSchwellenbach
- @ChristianFeldmann

The pull requests #5 are open and are being tracked.
The current scores are: current scores

**Comment by ChristianFeldmann** [comment]
#prbot add user @BitmovinPRBot9000TestUser1

**Comment by ghost** [comment]
The user @BitmovinPRBot9000TestUser1 was successfully added. The current scores are:
current scores

**Comment by ChristianFeldmann** [comment]
#prbot add user @BitmovinPRBot9000TestUser2

**Comment by ghost** [comment]
The user @BitmovinPRBot9000TestUser2 was successfully added. The current scores are:
current scores

**Review by BitmovinPRBot9000TestUser1 — APPROVED** [review]

**Comment by ChristianFeldmann** [comment]
#prbot help

**Comment by ghost** [comment]
Hi! I am the Bitmovin 9000 PR bot. I became operational at the H.A.C.K.A.T.O.N plant Berlin on the 23 rd of November 2018. My instructor was Mr. Feldmann and he taught me to sing a song. If you'd like to hear it I can sing it for you.
I want to help to track who did how many lines of reviews in order to more evenly distribute them. Every time a pull request is opened, I will show the current scores and suggest who could do the review. I am just giving suggestions so requesting reviews is still up to you.
Here is a list of commands you can use to control what happens:

### Initialization of repos
'''
#prbot initialize <user_1> <user_2> ...
#prbot uninitialize IAMREALLAYSURE <repo_name>
'''
### Add / remove user
Add and remove users from the tracking :
'''
#prbot add user <user_name>
”#prbot remove user <user_name>
'''
### Track Pull-requests
By default, every new PR is tracked but maybe you want to control it manually:
'''
#prbot track PR <pr_number>
#prbot untrack PR <pr_number>
'''
### Help'''
#prbot help
'''

**Pull request merged**
